site_name: Certificado de Profesionalidad IFCD0211
site_url: https://jbeteta-ies.github.io/IFCD0211/
theme:
  name: material
  features:
    - content.code.copy

markdown_extensions:
  - toc:
      toc_depth: 0
  - admonition
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - codehilite
  - attr_list

nav:
  - Inicio: index.md
  - Contenidos:
      - MF0966_3:
          - UF2213: 
            - Introducción: https://jbeteta-ies.github.io/BBDD/temas/T01/T01_BBDD.html
            - Modelo Entidad-Relación: https://jbeteta-ies.github.io/BBDD/temas/T02/T02_EER.html
            - Modelo Relacional: https://jbeteta-ies.github.io/BBDD/temas/T03/T03_MODELO_RELACIONAL.html
          - UF2214: 
            - Modelo Físico (I) Introducción: https://jbeteta-ies.github.io/BBDD/temas/T04/BD_T4_SQL_01.html
            - Modelo Físico (II) Simple SQL: https://jbeteta-ies.github.io/BBDD/temas/T04/BD_T4_SQL_02.html
            - Modelo Físco (III) SQL Avanzado: https://jbeteta-ies.github.io/BBDD/temas/T04/BD_T4_SQL_03.html
            - Modelo Físico (IV) Transacciones: https://jbeteta-ies.github.io/BBDD/temas/T04/BD_T4_SQL_04.html
            - Modelo Físico (V) Procedimientos almacenados: https://jbeteta-ies.github.io/BBDD/temas/T04/BD_T4_SQL_05.html
          - UF2215: 
            - Introducción: content/MF_0966_3/UF2215/index.md
            - T01 Fundamentos de JS: 
              - 1.1 Configuración del entorno de desarrollo: content/MF_0966_3/UF2215/unidad01_11.md
              - 1.2 Variables, Tipos de Datos y Operadores: content/MF_0966_3/UF2215/unidad01_12.md
              - 1.3 Estructuras básicas condicionales: content/MF_0966_3/UF2215/unidad01_13.md
              - 1.4 Bucles: content/MF_0966_3/UF2215/unidad01_14.md
              - 1.5 Uso avanzado de Números, cadenas y fechas: content/MF_0966_3/UF2215/unidad01_15.md
              - 1.6 Ejercicios: content/MF_0966_3/UF2215/unidad01_16.md
            - T02 Arrays y Objetos: 
              - 2.1 Arrays: content/MF_0966_3/UF2215/unidad02_21.md
              - 2.2 Objetos: content/MF_0966_3/UF2215/unidad02_22.md
              - 2.3 Persistencia: content/MF_0966_3/UF2215/unidad02_23.md
              - 2.4 Clases: content/MF_0966_3/UF2215/unidad02_24.md
            - T03 Funciones y manejo de errores: 
              - 3.1 Funciones: content/MF_0966_3/UF2215/unidad03_31.md
              - 3.2 Manejo de errores: content/MF_0966_3/UF2215/unidad03_32.md
              - 3.3 Asincronía en JS: content/MF_0966_3/UF2215/unidad03_33.md
      - MF0967_3:
          - UF2216: content/MF_0967_3/UF2216.md
          - UF2217: content/MF_0967_3/UF2217.md
          - UF2218: content/MF_0967_3/UF2218.md
      - MF0968_3:
          - UF1643: content/MF_0968_3/UF1643.md
          - UF1644: content/MF_0968_3/UF1644.md
      - MP0459:
          - Prácticas: content/MP0459/Practicas.md
